version: 2
jobs:
  build:
    - image: circleci/node:7.10 
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-npm-deps-{{ checksum "package.json" }}
        - v1-npm-deps
    - run: npm i
        
    - save_cache:
        key: v1-npm-deps-{{ checksum "package.json" }}
        paths:
        - node_modules
workflows:
  version: 2
  workflow:
    jobs:
    - build

